# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='id',
        ),
        migrations.AlterField(
            model_name='call',
            name='callid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='ccid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
