# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180210_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='text',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
