# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Conversation Time'),
        ),
    ]
