# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180210_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='cce',
            fields=[
                ('callid', models.IntegerField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=500)),
                ('service_provider', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('ccid', models.IntegerField()),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Conversation Time')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total_calls', models.IntegerField()),
                ('total_minutes', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('sentiment', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
