# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cce_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cce',
        ),
    ]
